changelog:
  categories:
    - title: Enhancement
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fixes
    - title: Documentation
      labels:
        - documentation
  exclude:
    labels:
      - dependencies
    authors:
      - dependencies
