name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # ローカルアクション呼び出し前にチェックアウトが必要
      - uses: ./.github/actions/dump/ # ローカルアクションの呼び出し
        id: dump
        with:
          enable-context: 'true'
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
